### ISSUE TITLE
Stake ERC-20 treasury tokens back into JB

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-juicehouse#108]
Right now, there's the option to unstake tokens into ERC-20s. But there's no way to stake ERC-20s back into the protocol.

This has been a question many folks at SharkDAO have been curious about as it's created utility for unstaking (with LPs). 

It would help to give people the option to stake back into the protocol where they feel their funds are safer and used, even if there isn't a direct utility to doing so at the moment. It's slightly disorienting to be able to unstake but not stake back in.

**Comment by peripheralist** [comment]
done
