### ISSUE TITLE
tap amounts are off due to fee

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-juicehouse#111]
![image](https://user-images.githubusercontent.com/77952627/131232266-e5d969e1-0f80-4bee-8410-c35ad6e55b4d.png)
![image](https://user-images.githubusercontent.com/77952627/131232267-06018464-eb72-4f3e-b5a3-280b5ef77bb5.png)
![image](https://user-images.githubusercontent.com/77952627/131232269-ce387f5f-1cba-403a-a24f-27d698f0d36c.png)

**Comment by peripheralist** [comment]
fixed
