### ISSUE TITLE
Reduce network calls from looking up ENS names

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-juicehouse#112]
The FormattedAddress component accounts for a huge chunk of Infura requests used by the app—especially on the project dashboard where lookups are done for mods and events. 

Could we cache ENS names locally to avoid refetching for known addresses each time a page re-renders?

**Comment by odd-amphora** [comment]
seems very reasonable and very doable

**Comment by odd-amphora** [comment]
but time should still be considered. if you infinitely cache and ENSs expire that could be messy

**Comment by odd-amphora** [comment]
since infura imposes a daily limit, it could just be reset daily

**Comment by peripheralist** [comment]
Yep, a 24hr cache sounds good to me

**Comment by peripheralist** [comment]
done
