### ISSUE TITLE
Duration = 0 days looks weird in the reconfigure UI. Maybe "Flexible duration"?

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-juicehouse#115]
![image](https://user-images.githubusercontent.com/77952627/131587747-ead8d66f-decc-4aa4-b524-388979236b6b.png)

**Comment by peripheralist** [comment]
setting this to "not set" for now for consistency with project create form

![image](https://user-images.githubusercontent.com/79433522/132586165-df1c27e9-c204-4feb-984a-407cb18c4ef2.png)
