### ISSUE TITLE
Setting discount rate on deploy not possible 

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-juicehouse#127]
The "Incentives" step doesn't show up on deploy if there is no target being set. But a project might still want to set a discount rate if there is a duration. 

![image](https://user-images.githubusercontent.com/77952627/132580597-4a0f30f4-1d06-4311-bd63-08d3f958f8e4.png)

**Comment by peripheralist** [comment]
fixed. if duration > 0 and no funding target, the incentives form is now shown with only the discount rate option

the form is only hidden completely if duration == 0 and no funding target is set
