### ISSUE TITLE
Better method for getting FC history

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-juicehouse#134]
current functionality leads to excessive looping

**Comment by peripheralist** [comment]
@mejango can we add in a getter to the v2 projects contract that allows getting a funding cycle by number instead of ID like so:

`fundingCycleOf(projectId, fcNumber)`

**Comment by mejango** [comment]
In V2 the ID of a funding cycle can be constructed via its projectID and its number. woop woop
