### ISSUE TITLE
Clicking outside of `ant-drawer-content-wrapper` should not mark Design project step as completed.

### ISSUE THREAD

**Issue by nnnnicholas** [jbx-protocol/juice-juicehouse#138]
**Behavior**
When configuring a new project using the `Design your project` interface, clicking outside of the `ant-drawer-content-wrapper` marks the current step as complete. Note: this does not apply to the initial `Identity` step of the configuration.

**Expected Behavior**
Clicking outside of `ant-drawer-content-wrapper` should *not* mark the step as completed. Users should either have to click Save, or, changes should be automatically saved and clicking outside of the `ant-drawer-content-wrapper` should maintain current behavior.

https://user-images.githubusercontent.com/1418561/133160549-8a9e32c7-a1b3-46fd-9bca-657dfe4ee58b.mov

**Comment by peripheralist** [comment]
this is actually intended behavior—some of these steps can be skipped without needing to save anything, making the save button feel a little awkward.

that said, let's make this feel good, and if having the step completed automatically feels more awkward then we can make all "save" buttons required

**Comment by nnnnicholas** [comment]
you know i'm not _so_ confident on this request. it feels a bit non-standard but i'll close as this isn't urgent or significant IMO.
