### ISSUE TITLE
Add an "upload file" button that works just like the logo uploader

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-juicehouse#65]
append the url to the memo. Allow users to add many images.

![image](https://user-images.githubusercontent.com/77952627/128965334-880b8b71-47ba-4031-bd04-3d5c75e02481.png)

**Comment by mejango** [comment]
![image](https://user-images.githubusercontent.com/77952627/128965470-b3bd6b01-067a-4fb0-8368-c341580f937b.png)

**Comment by peripheralist** [comment]
done
